# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&eConditionalText &8| '

## Plugin log level
# SEVERE - Errors
# WARNING - Warnings
# INFO - Normal user information
# FINE - Debug messages
# (...lower levels are not used)
log-level: INFO

# Configure the placeholder identifier.
# PAPI format: %<identifier>_(params)%
placeholder-identifier: 'conditionaltext'

# What to return when no rules match the output.
empty-output: 'no-match'

# Define default formats
formats:
  time: 'H:m:s'