name: ${project.name}
main: ${project.groupId}.ConditionalTextPlugin
version: ${project.version}
authors: [ Wertik1206 ]
softdepend: [ PlaceholderAPI ]
commands:
  conditionaltext:
    description: Main plugin command.
    aliases: [ ct, condtext, ctext ]