name: ${project.name}
main: ${project.groupId}.ConditionalTextPlugin
version: ${project.version}
authors: [ qwz ]
softdepend: [ PlaceholderAPI ]
api-version: 1.13
commands:
  conditionaltext:
    description: Main plugin command.
    aliases: [ ct, condtext, ctext ]