# Settings configuration for ${project.name}
#
# Version: ${project.version}

# Define a name for the setting.
setting-one:
  # Set a placeholder to base conditions on.
  placeholder: '%player_health%'
  # Define the rules to parse by.
  # Rules are checked top to bottom one by one, whichever passes first is used.
  rules:
    # if player's health is below 3,
    # the placeholder %conditionaltext_setting-one% outputs "You're about to die!"
    - "<3;&cYou're about to die!"
    - "<6;&eA bit low, but fine."
    - "&aHealthy as ever!"

time-setting:
  # You can add extra arguments to placeholders.
  # The $0 argument would be filled by using the following: %conditionaltext_time-setting_world% ( $0 = world )
  placeholder: '%world_time_$0%'
  rules:
    - '<10:0:0;&7&ogooob moorning.'
    - '<14:0:0;&7&otime for lunch, munch munch.'
    - '&7&oNap tiiiime!'